### ISSUE TITLE
make target 'build-docker-image' doesn't exist

### ISSUE THREAD

**Issue by b2cc** [gerald1248/openshift-backup#6]
Thank you for your hard work, this finally looks like a sensible solution to backup project data! I was just going to test this out and noticed that the makefile doesn't contain the "build-docker-image" target, which is mentioned in the README.md file. Could you add that to the Makefile?

**Comment by gerald1248** [comment]
Thanks for suggestion, will do.

**Comment by gerald1248** [comment]
Build target is now available.
