### ISSUE TITLE
syntax errors in shell script project_export.sh

### ISSUE THREAD

**Issue by b2cc** [gerald1248/openshift-backup#7]
The shell script `project_export.sh` which comes with the docker image "gerald1248/openshift-backup" produces the following error during execution (once for every project it loops through):

```
bash-4.2$ openshift-backup
Processing 'default'
/usr/bin/project_export.sh: project_export.sh: line 135: syntax error near unexpected token `!'
...
Exporting 'serviceaccounts' resources to default/serviceaccounts.json
/usr/bin/project_export.sh: line 501: ${BACKUP_SECRETS}: command not found

```

The line 135 reads:
`if jq '.spec.triggers[].type' "${PROJECT}/dc_${dc}.json" | ! grep -q "ImageChange"; then`

I suspect there is a pipe missing. If it's changed to:

`if jq '.spec.triggers[].type' "${PROJECT}/dc_${dc}.json" || ! grep -q "ImageChange"; then`

it seems to work. Not sure about what's going on on line 501 while exporting secrets though.

**Comment by gerald1248** [comment]
Thanks & apologies for errors, will fix ASAP.

**Comment by b2cc** [comment]
thanks for responding! just wanted to add some suggestions I noticed while testing the backups:
 - for larger clusters the limitrange seems to be too strict. I got a pod get oomkill'd while compressing the json files (perhaps tar/gzip would be more efficient). no big deal though.
 - if more than one backup is taken per day, the already existing backup gets overwritten since the file is suffixed with YYYYMMDD only. expanding the suffix to something like YYYMMDD-HHMM would probably fix that.

thanks for your support and consideration!

**Comment by gerald1248** [comment]
@b2cc thanks again for alerting me to this problem. There were two issues:

* dc/svc processing, now simplified and brought into line with the other resource types
* missing parameter for env variable BACKUP_SECRETS (in template.yml and template-non-admin-job.yml)

Issue is ready for re-testing.

**Comment by gerald1248** [comment]
PS I forgot to mention a third issue with backward compatibility. On my 3.9 cluster the RBAC apiVersion led to errors.
PPS Thanks for the suggestions re limitrange and datestamp. Will fold these in shortly.

**Comment by b2cc** [comment]
@gerald1248: our comments just overlapped... thanks for picking those up, will test shortly and respond.
PS: I just noticed the missing BACKUP_SECRETS variable while browsing through the dc. Must have escaped me yesterday somehow, sorry for that.

**Comment by gerald1248** [comment]
Have adjusted limits and datestamp. Happy to fine-tune if not quite right.

**Comment by b2cc** [comment]
Seems to work as described/expected now. I just re-setup the backup project and let it do backups every 10 minutes, no errors so far. I guess this can be closed now. thanks again for your support and the quick fix!

**Comment by gerald1248** [comment]
Thanks for re-testing!
